/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    app_version: AppVersion;
    banner_screen: BannerScreen;
    banner_manage: BannerManage;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    app_version: AppVersionSelect<false> | AppVersionSelect<true>;
    banner_screen: BannerScreenSelect<false> | BannerScreenSelect<true>;
    banner_manage: BannerManageSelect<false> | BannerManageSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_version".
 */
export interface AppVersion {
  id: string;
  sqlId?: number | null;
  appVersion: string;
  textMessage: string;
  redxOverlayDisplayDays: number;
  webTnCTimestamp: string;
  vigAutoExtendDate: string;
  copyOfVersion: 'version1' | 'version2' | 'version3';
  isSilentOTAEnabled: 1 | 0;
  isLiteRechargeBannerShown: 1 | 0;
  isPaletroAPICall?: (1 | 0) | null;
  isPaletroPromotionalTitleShown: 1 | 0;
  isViFinanceDown: 1 | 0;
  status: 1 | 0;
  isPrepaidViShopDisabled: 1 | 0;
  isPostpaidViShopDisabled: 1 | 0;
  isCOCPViShopDisabled: 1 | 0;
  isNonViViShopDisabled: 1 | 0;
  isShopDown: 1 | 0;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_screen".
 */
export interface BannerScreen {
  id: string;
  numericId?: number | null;
  /**
   * Enter banner name as DisneyHotstar_Rail1 for Rail1, for banner - DisneyHotstar_Banner, for Rail2 - DisneyHotstar_Rail2
   */
  screenName: string;
  description?: string | null;
  title: string;
  hindiTitle?: string | null;
  screenHeader?: string | null;
  subHeader?: string | null;
  isTimestampCheck: 'true' | 'false';
  isComponent: 'true' | 'false';
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_manage".
 */
export interface BannerManage {
  id: string;
  screen: string | BannerScreen;
  circle: 'north' | 'south' | 'east' | 'west';
  loginType: 'primary' | 'secondary' | 'both';
  brand: 'brand-a' | 'brand-b' | 'brand-c';
  lob: 'lob-1' | 'lob-2' | 'lob-3';
  /**
   * Enter internal link Eg. /recharge
   */
  notifiedInternalLink?: string | null;
  isNotified: 'active' | 'inactive';
  /**
   * Select the device OS
   */
  deviceOS?: ('active' | 'inactive') | null;
  appVersion?: string | null;
  bannerRank?: ('rank-1' | 'rank-2' | 'rank-3') | null;
  status: 'active' | 'inactive';
  updateComment: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'app_version';
        value: string | AppVersion;
      } | null)
    | ({
        relationTo: 'banner_screen';
        value: string | BannerScreen;
      } | null)
    | ({
        relationTo: 'banner_manage';
        value: string | BannerManage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app_version_select".
 */
export interface AppVersionSelect<T extends boolean = true> {
  sqlId?: T;
  appVersion?: T;
  textMessage?: T;
  redxOverlayDisplayDays?: T;
  webTnCTimestamp?: T;
  vigAutoExtendDate?: T;
  copyOfVersion?: T;
  isSilentOTAEnabled?: T;
  isLiteRechargeBannerShown?: T;
  isPaletroAPICall?: T;
  isPaletroPromotionalTitleShown?: T;
  isViFinanceDown?: T;
  status?: T;
  isPrepaidViShopDisabled?: T;
  isPostpaidViShopDisabled?: T;
  isCOCPViShopDisabled?: T;
  isNonViViShopDisabled?: T;
  isShopDown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_screen_select".
 */
export interface BannerScreenSelect<T extends boolean = true> {
  numericId?: T;
  screenName?: T;
  description?: T;
  title?: T;
  hindiTitle?: T;
  screenHeader?: T;
  subHeader?: T;
  isTimestampCheck?: T;
  isComponent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_manage_select".
 */
export interface BannerManageSelect<T extends boolean = true> {
  screen?: T;
  circle?: T;
  loginType?: T;
  brand?: T;
  lob?: T;
  notifiedInternalLink?: T;
  isNotified?: T;
  deviceOS?: T;
  appVersion?: T;
  bannerRank?: T;
  status?: T;
  updateComment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}